# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: 'Green Circuits'
# Website URL
baseURL: 'https://da-johnson.github.io/'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
    extensions:
      table: true
    renderHooks:
      link:
        enableDefault: true
  highlight:
    lineNos: false
seo:
  site_type: Person
  open_graph: true
  twitter_cards: true
  description: "Synthetic biology meets sustainability. Personal site of Alex Johnson, focused on membrane proteins, cell-free systems, and ecological bioengineering."
  org_name: "Alex Johnson"
